apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
  namespace: default
data:
  default.conf: |
    server {
      listen 80;

      location /healthz {
        return 200 '{"service":"frontend","status":"healthy"}';
        add_header Content-Type application/json;
      }

      location /api/ {
        proxy_pass http://bff-svc/api/;
      }

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }
