apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-nginx-conf
  namespace: default
data:
  default.conf: |
    server {
      listen 80;

      location /healthz {
        return 200 '{"service":"notification","status":"healthy"}';
        add_header Content-Type application/json;
      }

      location / {
        return 200 '{"service":"notification","status":"sent"}';
        add_header Content-Type application/json;
      }
    }
