apiVersion: v1
kind: ConfigMap
metadata:
  name: user-svc-nginx-conf
  namespace: default
data:
  default.conf: |
    server {
      listen 80;

      location /healthz {
        return 200 '{"service":"user","status":"healthy"}';
        add_header Content-Type application/json;
      }

      location = /users {
        proxy_pass http://user-svc-read:3000/users;
      }

      location = /users/create {
        proxy_set_header Prefer "return=representation";
        proxy_pass http://user-svc-write:3000/users;
      }
    }
